sudo: false
language: cpp
cache: ccache
addons:
  apt:
    packages:
    - cmake
    - libssl-dev
    - libprotobuf-dev
    - protobuf-compiler
    - liblzma-dev
    - zlib1g-dev
    - liblzo2-dev
script:
  - cd tools/tartool
  - mkdir objdir
  - cd objdir
  - cmake ../
  - make
  - cd ../../
  - mkdir objdir
  - cd objdir
  - cmake ../
  - make
